services:
  nginx:
    build: nginx/
    links:
      - php-fpm
    ports:
      - 8080:80

  php-fpm:
    build: php-fpm/
    volumes:
      - .:/var/www/html
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_SENTINEL_HOST=redis-sentinel

  redis:
    image: redis
    ports:
      - 6379:6379

  redis-sentinel:
    image: redis
    volumes:
      - ./sentinel.conf://etc/sentinel.conf
    ports:
      - 26379:26379
    command: redis-sentinel /etc/sentinel.conf

  phpunit:
    build: php-fpm/
    volumes:
      - .:/var/www/html
    links:
      - redis
      - nginx
    environment:
      - REDIS_HOST=redis
      - REDIS_SENTINEL_HOST=redis-sentinel
